In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('./folk/melody.csv')
df.head(10)

,eventid,melid,onset,pitch,duration,period,division,bar,beat,tatum,subtatum,num,denom,beatprops,beatdur,tatumprops
0,1,1,0.0,67.0,0.5,4,1,0,4,1,0,4,2,None,0.5,None
1,2,1,0.5,70.0,0.5,4,1,1,1,1,0,4,2,None,0.5,None
2,3,1,1.0,70.0,0.5,4,1,1,2,1,0,4,2,None,0.5,None
3,4,1,1.5,72.0,0.5,4,1,1,3,1,0,4,2,None,0.5,None
4,5,1,2.0,72.0,0.5,4,1,1,4,1,0,4,2,None,0.5,None
5,6,1,2.5,74.0,1.0,4,1,2,1,1,0,4,2,None,0.5,None
6,7,1,3.5,74.0,1.0,4,1,2,3,1,0,4,2,None,0.5,None
7,8,1,5.0,74.0,1.0,4,1,3,2,1,0,4,2,None,0.5,None
8,9,1,6.0,74.0,0.5,4,1,3,4,1,0,4,2,None,0.5,None
9,10,1,6.5,74.0,0.5,4,1,4,1,1,0,4,2,None,0.5,None

In [19]:
# create a mask
mask = df['melid'] <= 1000

# apply the mask to select rows where melid is less than 1000
pitch_column = df.loc[mask, 'pitch']

pitch_column_int = pitch_column.apply(lambda x: int(x))

pitch_column_int.shape

(44850,)

In [20]:
pitch_column_int.to_csv('pitch_column.txt', header=None, index=None, sep=' ')