In [21]:
import pandas as pd
from simplefractions import *

In [2]:
df = pd.read_csv('../../../datasets/folk_melody.csv')
df.head(10)

,eventid,melid,onset,pitch,duration,period,division,bar,beat,tatum,subtatum,num,denom,beatprops,beatdur,tatumprops
0,1,1,0.0,67.0,0.5,4,1,0,4,1,0,4,2,None,0.5,None
1,2,1,0.5,70.0,0.5,4,1,1,1,1,0,4,2,None,0.5,None
2,3,1,1.0,70.0,0.5,4,1,1,2,1,0,4,2,None,0.5,None
3,4,1,1.5,72.0,0.5,4,1,1,3,1,0,4,2,None,0.5,None
4,5,1,2.0,72.0,0.5,4,1,1,4,1,0,4,2,None,0.5,None
5,6,1,2.5,74.0,1.0,4,1,2,1,1,0,4,2,None,0.5,None
6,7,1,3.5,74.0,1.0,4,1,2,3,1,0,4,2,None,0.5,None
7,8,1,5.0,74.0,1.0,4,1,3,2,1,0,4,2,None,0.5,None
8,9,1,6.0,74.0,0.5,4,1,3,4,1,0,4,2,None,0.5,None
9,10,1,6.5,74.0,0.5,4,1,4,1,1,0,4,2,None,0.5,None

In [41]:
# create a mask
mask = df['melid'] <= 100

# apply the mask to select rows where melid is less than 1000

pitch_duration_columns = df.loc[mask, ['pitch','duration','num']]


pitch_duration_columns['pitch'] = pitch_duration_columns['pitch'].apply(lambda x: int(x))
pitch_duration_columns['duration'] = pitch_duration_columns.apply(lambda row: row['duration'] / row['num'], axis=1)
pitch_duration_columns['duration'] = pitch_duration_columns['duration'].apply(lambda x: simplest_from_float(x))
pitch_duration_columns = pitch_duration_columns.drop('num', axis=1)


pitch_duration_columns.head(20)

# pitch_column_int.shape

    pitch duration
0      67      1/8
1      70      1/8
2      70      1/8
3      72      1/8
4      72      1/8
5      74      1/4
6      74      1/4
7      74      1/4
8      74      1/8
9      74      1/8
10     76      1/8
11     77      1/8
12     74      1/8
13     74      1/4
14     74      1/8
15     74      1/8
16     76      1/8
17     77      1/8
18     74      1/8
19     75      1/4

In [43]:
pitch_duration_columns.to_csv('pitch_<100.txt', header=None, index=None, sep=' ')